---
- name: Check kubectl version
  shell: "kubectl version 2>&1 | grep {{ kubectl_version }}"
  failed_when: false
  changed_when: false
  register: kubectl_versions_match

- include: download.yml
  when: kubectl_versions_match.rc != 0

- name: copy kubectl to /usr/local/bin/
  copy:
    remote_src: yes
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
  when: kubectl_versions_match.rc != 0
...
